import { useEffect, useRef, useState, type ReactNode } from 'react';
import { X, ArrowUpRight, Sun, CloudSun, CloudRain, Settings2, ChevronDown, Users, Check, Sparkles, Zap, BookOpen, Clock3 } from 'lucide-react';
import { type Mapping, type Snapshot, type Weather, currentPeriod, minuteOfDay, timeMinutes, weatherCondition } from './model';
import { classroomRequest, erpLink, type ClassroomData } from './data';
import { TakeAttendance } from './TakeAttendance';
import { useWhiteboardStore } from '../store';
import type { WidgetKind } from '../classroom/model';
import './dashboard.css';

export function DashboardModal({ title, close, children }: {title: string; close: () => void; children: ReactNode}) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const d = ref.current; const previous = document.activeElement as HTMLElement | null; d?.showModal(); return () => { d?.close(); previous?.focus(); }; }, []);
  return <dialog className="live-dialog" ref={ref} onCancel={close} onClick={e => { if (e.target === e.currentTarget) close(); }} aria-label={title}><header><h2>{title}</h2><button aria-label={`Close ${title}`} onClick={close}><X size={22} /></button></header>{children}</dialog>;
}
export function ConnectionDialog({ data, close }: {data: ClassroomData; close: () => void}) {
  const [credential, setCredential] = useState(''), [password, setPassword] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [chosen, setChosen] = useState(''), [device, setDevice] = useState(data.mapping?.device || ''), [timezone, setTimezone] = useState(data.mapping?.timezone || 'Asia/Kolkata');
  const classes = data.session?.classes || [];
  const previous = classes.find(c => c.classId === data.mapping?.classId && c.sectionId === data.mapping?.sectionId);
  const selected = classes.some(c => `${c.classId}/${c.sectionId}` === chosen) ? chosen : previous ? `${previous.classId}/${previous.sectionId}` : classes.length === 1 ? `${classes[0].classId}/${classes[0].sectionId}` : '';
  const connectionError = (e: unknown) => {
    const code = e instanceof Error ? e.message : '';
    return code === 'CLASS_TEACHER_REQUIRED' ? 'This account has no class teacher assignment. Ask the school office to update your class and section in ERP.' : code === 'CLASS_ACCESS_DENIED' ? 'Your account is not authorized for this classroom. Sign in with its class teacher account.' : code === 'TRY_LATER' ? 'Too many sign-in attempts. Please wait five minutes and try again.' : code === 'SIGN_IN_REQUIRED' ? 'Please check your ERP username and password, then sign in again.' : 'The school ERP could not be reached. Please try again shortly.';
  };
  return <DashboardModal title="Classroom connection" close={close}>
    {!data.ready ? <><p>The classroom connection service is unavailable. Your whiteboard and classroom tools are ready to use.</p><p>When connected, sign in with your existing class teacher ERP account to open your assigned classroom.</p><button className="live-button" onClick={data.refresh}>Retry connection</button><a className="live-button" href={erpLink(data.erpBase, 'teacher-portal/login')} target="_blank" rel="noopener noreferrer">Open school ERP <ArrowUpRight size={17}/></a></> : !data.session ? <form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { const s = await classroomRequest('login', { credential, password }); setPassword(''); data.setSession(s); } catch (e) { setPassword(''); setError(connectionError(e)); } finally { setBusy(false); } }}>
      <p>Sign in with your existing class teacher ERP account. Only the class and section assigned to you as class teacher will be available.</p>
      <label>Email or username<input autoComplete="username" required value={credential} onChange={e => setCredential(e.target.value)} /></label>
      <label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e => setPassword(e.target.value)} /></label><button className="live-button live-primary" disabled={busy}>{busy ? 'Signing in…' : 'Class teacher sign in'}</button>
    </form> : <form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { const c = classes.find(c => `${c.classId}/${c.sectionId}` === selected); if(!c) return; const result = await classroomRequest('mapping', { ...c, device, timezone }); data.saveMapping(result.mapping); close(); } catch (e) { setError(connectionError(e)); } finally { setBusy(false); } }}>
      <p>Signed in as <strong>{data.session.name || 'class teacher'}</strong>. Choose your classroom to connect this smartboard.</p><label>Your class and section<select required value={selected} onChange={e => setChosen(e.target.value)}><option value="">Choose your classroom</option>{classes.map(c => <option key={`${c.classId}/${c.sectionId}`} value={`${c.classId}/${c.sectionId}`}>{c.grade} · {c.section}</option>)}</select></label><label>Smartboard name<input maxLength={80} value={device} onChange={e => setDevice(e.target.value)} placeholder="Classroom smartboard" /></label><label>Timezone<input required value={timezone} onChange={e => setTimezone(e.target.value)} /></label><button disabled={busy || !selected} className="live-button live-primary">{busy ? 'Connecting…' : 'Open my classroom'}</button><button type="button" disabled={busy} className="live-button" onClick={() => { setError(''); void data.logout(); }}>Sign out</button>
    </form>}
    <p className="live-muted">Student lists stay in memory for this session. Only the classroom choice is saved on this device.</p>
    {error && <p role="alert">{error}</p>}
  </DashboardModal>;
}

type Props = { now: number; mapping: Mapping | null; snapshot: Snapshot | null; weather: Weather | null; presenting: boolean; data: ClassroomData; addWidget: (kind: WidgetKind) => void; onWhiteboard: () => void; onPresent: () => void; onConnection: () => void; preview: boolean; onPreview: (enabled: boolean, grade?: string, scenario?: string) => void };
export function ClassroomHome({ now, mapping, snapshot, weather, presenting, data, addWidget, onWhiteboard, onPresent, onConnection, preview, onPreview }: Props) {
  const [list, setList] = useState<'present'|'absent'|null>(null), [taking, setTaking] = useState(false), [actions, setActions] = useState(false), [more, setMore] = useState(false), [editLearning, setEditLearning] = useState(false), [learning, setLearning] = useState<string|null>(null), [notes, setNotes] = useState(''), [qr, setQr] = useState(false);
  const [previewScenario, setPreviewScenario] = useState('normal');
  useEffect(()=>{ if(!data.session && !preview) setNotes(''); },[data.session,preview]);
  const timezone = mapping?.timezone || 'Asia/Kolkata';
  const state = currentPeriod(snapshot?.timetable.periods || [], now, timezone, snapshot?.timetable.holiday);
  const hour = Math.floor(minuteOfDay(now, timezone) / 60);
  const greeting = hour < 12 ? 'Good morning' : hour < 17 ? 'Good afternoon' : 'Good evening';
  const attendance = snapshot?.attendance;
  const markUrl = erpLink(data.erpBase, 'teacher-portal/attendance');
  const objective = learning ?? snapshot?.learning;
  useEffect(() => { if(presenting) { setTaking(false); setList(null); setActions(false); setMore(false); setEditLearning(false); setQr(false); } }, [presenting]);
  const openExisting = (kind: 'lesson'|'website'|'youtube') => { onWhiteboard(); const s = useWhiteboardStore.getState(); if(kind === 'lesson') s.openLibrary('templates'); else if(kind === 'website') s.setWebAppDialogOpen(true); else s.setYouTubeDialogOpen(true); };
  const publicNotices = snapshot?.notices.filter(n => !presenting || n.public) || [];
  const nowTitle = snapshot?.timetable.holiday || state.current?.subject || (snapshot?.timetable.complete ? 'A little room to learn.' : mapping ? 'Ready for today’s learning.' : 'Welcome to your classroom.');
  return <div className="live-home" aria-label="Live classroom dashboard">
    {preview && presenting && <div className="live-preview"><span>Preview · sample data only</span></div>}
    {preview && !presenting && <div className="live-preview"><span>Preview · sample data only</span><select aria-label="Preview classroom" value={mapping?.grade} onChange={e => onPreview(true, e.target.value, previewScenario)}>{['KG','Grade 1','Grade 2','Grade 3','Grade 4'].map(g => <option key={g}>{g}</option>)}</select><select aria-label="Preview scenario" value={previewScenario} onChange={e => { setPreviewScenario(e.target.value); onPreview(true, mapping?.grade, e.target.value); }}><option value="normal">Attendance marked</option><option value="unmarked">Not marked</option><option value="all">All present</option><option value="break">Break</option><option value="lunch">Lunch</option><option value="empty">No classes</option><option value="holiday">Holiday</option><option value="offline">ERP unavailable</option><option value="weather">Weather unavailable</option></select><button onClick={() => onPreview(false)}>Exit preview</button></div>}
    <div className="live-intro"><div><p className="live-eyebrow">A GOOD DAY TO DISCOVER</p><h1>{greeting}{mapping ? `, ${mapping.grade}` : ''}<span>!</span></h1></div>{!presenting && <button className="live-button live-quick" onClick={() => setActions(true)}><Zap size={18}/>Quick actions<ChevronDown size={16}/></button>}</div>
    <div className="live-cards">
      {!presenting && <section className="live-card live-attendance" aria-label="Today's attendance"><h2><Users size={19}/>Today’s attendance</h2>
        {data.loading && !snapshot ? <div className="live-skeleton" aria-label="Loading attendance"/> : attendance ? <><div className="live-enrolled"><b>{attendance.total}</b><span>students in our class</span></div>{attendance.marked ? <><div className="live-counts"><button onClick={() => setList('present')}><span className="live-dot"/><b>{attendance.present}</b><span>Present</span></button><button onClick={() => setList('absent')}><span className="live-dot live-absent"/><b>{attendance.absent}</b><span>Absent</span></button></div><div className="live-attendance-rate"><span style={{width:`${attendance.percentage || 0}%`}}/></div><p><strong>{attendance.percentage ?? '—'}%</strong> attendance{attendance.late > 0 ? ` · ${attendance.late} late` : ''}</p>{attendance.unmarked > 0 && <p>{attendance.unmarked} not marked yet</p>}{attendance.other > 0 && <p>{attendance.other} other attendance status</p>}</> : <p className="live-empty-copy">Attendance not marked yet</p>}{!preview && mapping && <button className="live-text-link" onClick={() => setTaking(true)}>{attendance.marked ? 'Edit attendance' : 'Take attendance'}<ArrowUpRight size={16}/></button>}</> : <div className="live-attendance-empty"><Users size={34} strokeWidth={1.3}/><p>{data.error || preview ? 'Classroom data temporarily unavailable' : 'A little connection brings your class together.'}</p><button className="live-button" onClick={data.error ? data.refresh : onConnection}>{data.error ? 'Retry connection' : mapping ? 'Teacher sign in' : 'Connect classroom'}</button><small>Local classroom tools are always available.</small></div>}
      </section>}
      <section className="live-card live-current" aria-label="Current class"><div className="live-now-label"><span className="live-dot"/>{snapshot?.timetable.holiday ? 'TODAY' : state.current ? snapshot?.timetable.complete ? 'NOW' : 'YOUR LESSON NOW' : 'YOUR CLASSROOM'}{mapping && <span>{mapping.grade} · {mapping.section}</span>}</div><h2>{nowTitle}</h2>
        {state.current && !snapshot?.timetable.holiday ? <><p className="live-period-time">{state.current.start} – {state.current.end}</p>{!presenting && state.current.teacher && <p>Teacher: {state.current.teacher}</p>}<div className="live-remaining"><Clock3 size={17}/>{state.remaining} min remaining</div></> : <p className="live-current-description">{snapshot?.timetable.holiday ? 'Enjoy a pause. Your classroom tools are still here.' : snapshot?.timetable.complete ? 'No class is in progress right now.' : mapping ? 'Your tools are ready. Connect the class timetable to see what’s happening now.' : 'Your lessons, your tools, and your day — in one calm space.'}</p>}
        {!presenting && snapshot && !snapshot.timetable.complete && <p className="live-scope-note">Showing this teacher’s lessons only. The complete class timetable is not connected.</p>}
        {state.next && !snapshot?.timetable.holiday ? <div className="live-next"><span>NEXT</span><b>{state.next.subject}</b><time>{state.next.start}</time></div> : !presenting && <div className="live-current-actions"><button className="live-button live-primary" onClick={onWhiteboard}><BookOpen size={17}/>Open whiteboard</button>{!mapping && <button className="live-text-link" onClick={() => onPreview(true)}>Preview layout</button>}</div>}
      </section>
      <section className="live-card live-weather" aria-label="Today's weather"><h2>Today’s weather</h2>{weather ? <><div className="live-weather-top"><span>{weather.city}</span>{weather.code === 0 ? <Sun size={46}/> : weather.code <= 3 ? <CloudSun size={46}/> : <CloudRain size={46}/>}</div><strong>{Math.round(weather.temperature)}<small>°C</small></strong><p>{weatherCondition(weather.code)}</p><div className="live-weather-details"><span>Feels like {Math.round(weather.feelsLike)}°</span><span>Rain {weather.rain}%</span><span>{Math.round(weather.high)}° / {Math.round(weather.low)}°</span></div><a href="https://open-meteo.com/" target="_blank" rel="noopener noreferrer">{preview ? 'Sample weather' : 'Weather by Open-Meteo'}</a></> : <div className="live-weather-empty"><CloudSun size={56} strokeWidth={1.3}/><p>Weather taking a little break.</p><span>Your classroom is ready.</span></div>}</section>
    </div>
    <div className="live-lower"><details className="live-timeline"><summary>Today’s classes <ChevronDown size={17}/></summary>{snapshot?.timetable.holiday ? <p>{snapshot.timetable.holiday}</p> : snapshot?.timetable.periods.length ? <><p className="live-muted">{snapshot.timetable.complete ? 'Your day, at a glance.' : 'Your lessons only — not the full classroom timetable.'}</p><ol>{snapshot.timetable.periods.map(p => { const active = state.current?.id === p.id; const done = timeMinutes(p.end) <= minuteOfDay(now, timezone); return <li key={p.id} className={active ? 'is-current' : ''}>{done ? <Check size={17}/> : <span className="live-timeline-dot"/>}<time>{p.start || 'Time pending'}</time><span>{p.subject}</span>{active && <b>NOW</b>}</li>; })}</ol></> : <p>{mapping ? 'A verified classroom timetable is not available yet.' : 'Connect your classroom to bring in the day’s lessons.'}</p>}</details>
      <section className="live-learning"><div><Sparkles size={18}/><span>TODAY’S LEARNING</span></div>{objective ? <p>{objective}</p> : <p className="live-muted">A small goal. A bright beginning.</p>}{!presenting && <button onClick={() => setEditLearning(true)}>{objective ? 'Edit' : 'Add a learning objective'}</button>}</section>
      {!presenting && <button className="live-more" onClick={() => setMore(true)}>More for today <ArrowUpRight size={17}/></button>}
    </div>
    {presenting && publicNotices.length > 0 && <div className="live-announcement">{publicNotices[0].text}</div>}
    {!presenting && <div className="live-status"><span className={snapshot ? 'is-online' : ''}>ERP · {preview ? 'Sample data' : snapshot ? 'Connected' : data.error ? 'Unavailable' : 'Not connected'}</span><span>Attendance · {attendance?.marked ? 'Synced' : 'Waiting'}</span><span>Weather · {weather ? `${Math.max(0, Math.floor((now-weather.updatedAt)/60000))} min ago` : 'Unavailable'}</span><button onClick={onConnection}><Settings2 size={14}/>{mapping?.device || 'Set up smartboard'}</button>{data.session && <button onClick={() => { void data.logout(); }}>Sign out</button>}</div>}
    {!presenting && list && <DashboardModal title={list === 'present' ? 'Present students' : 'Absent students'} close={() => setList(null)}><div className="live-student-list">{(attendance?.students.filter(s => list === 'present' ? s.status === 'present' || s.status === 'late' : s.status === 'absent') || []).map(s => <div key={s.id}>{s.photo ? <img src={s.photo} alt="" referrerPolicy="no-referrer"/> : <span aria-hidden="true">{s.name.slice(0,1)}</span>}<b>{s.name}</b><small>{s.status}</small></div>)}</div>{list === 'absent' && attendance?.absent === 0 && <p>Everyone is here today.</p>}</DashboardModal>}
    {!presenting && editLearning && <DashboardModal title="Today's learning" close={() => setEditLearning(false)}><label>Learning objective<textarea maxLength={500} defaultValue={objective || ''} onChange={e => setLearning(e.target.value)} placeholder="We will learn how to…"/></label><p className="live-muted">Shown in Present Mode. Kept for this session only.</p><button className="live-button live-primary" onClick={() => setEditLearning(false)}>Done</button></DashboardModal>}
    {!presenting && more && <DashboardModal title="More for today" close={() => setMore(false)}>{snapshot?.students.some(s => s.birthday) && <section><h3>Birthday today</h3><p>{snapshot.students.filter(s => s.birthday).map(s => s.name).join(', ')}</p></section>}{snapshot?.events?.map((n,i) => <section key={`event-${i}`}><h3>{n.title}</h3><p>{n.text}</p></section>)}{snapshot?.homework.map((n,i) => <section key={`hw-${i}`}><h3>{n.subject} · {n.title}</h3><p>{n.text}</p></section>)}{publicNotices.map((n,i) => <section key={`notice-${i}`}><h3>{n.title}</h3><p>{n.text}</p><small>{n.public ? 'School announcement' : 'Teacher only'}</small></section>)}<label>Private teacher notes<textarea maxLength={2000} value={notes} onChange={e => setNotes(e.target.value)} placeholder="A reminder just for you…"/></label><p className="live-muted">Notes stay in this session and are hidden in Present Mode.</p></DashboardModal>}
    {!presenting && actions && <DashboardModal title="Quick actions" close={() => setActions(false)}><div className="live-actions-grid">{attendance && mapping && !preview ? <button onClick={() => { setActions(false); setTaking(true); }}>Take Attendance<ArrowUpRight size={16}/></button> : <a href={markUrl} target="_blank" rel="noopener noreferrer">Mark Attendance<ArrowUpRight size={16}/></a>}{[['Open Whiteboard',onWhiteboard],['Start Timer',()=>addWidget('timer')],['Random Student',()=>addWidget('random')],['Create Groups',()=>addWidget('groups')],['Open Today’s Lesson',()=>openExisting('lesson')],['Show QR Code',()=>setQr(true)],['Open Website',()=>openExisting('website')],['Play YouTube',()=>openExisting('youtube')],['Present Screen',onPresent]].map(([label,action])=><button key={String(label)} onClick={()=>{ setActions(false); (action as ()=>void)(); }}>{String(label)}<ArrowUpRight size={16}/></button>)}</div></DashboardModal>}
    {!presenting && qr && <QrDialog close={() => setQr(false)}/>}
    {!presenting && taking && attendance && mapping && !preview && <TakeAttendance data={data} mapping={mapping} attendance={attendance} close={() => setTaking(false)}/>}
  </div>;
}
function QrDialog({close}:{close:()=>void}) {
  const [url,setUrl] = useState('https://whiteboard.jaihind.school/'), [image,setImage] = useState(''), [error,setError] = useState('');
  useEffect(()=> { let active = true; setImage(''); setError(''); const timer = setTimeout(async()=> { try { const parsed = new URL(url); if(!['http:','https:'].includes(parsed.protocol) || parsed.username || parsed.password) throw new Error('Invalid URL'); const qr = await import('qrcode'); const data = await qr.toDataURL(parsed.href,{width:300,margin:2}); if(active) setImage(data); } catch { if(active) setError('Enter a full website address starting with https://'); } },200); return()=>{active=false;clearTimeout(timer);}; },[url]);
  return <DashboardModal title="Share a website" close={close}><label>Website address<input type="url" maxLength={2000} value={url} onChange={e=>setUrl(e.target.value)}/></label>{image && <img className="live-qr" src={image} alt="QR code for the website address above"/>}{error && <p role="alert">{error}</p>}<p className="live-muted">Created on this device. No link is sent to a QR service.</p></DashboardModal>;
}
