import { PenPreset } from '../PenPreset';

/** The second drawer: expressive, decorative and worksheet pens. */

export const FOUNTAIN_PEN: PenPreset = {
  id: 'fountain',
  name: 'Fountain',
  type: 'fountain',
  icon: '🖋',
  group: 'more',
  color: null,
  size: 3,
  opacity: 1,
  smoothing: 'high',
  pressureSensitivity: 'high',
  renderMode: 'tapered',
  compositeMode: 'source-over',
  lineCap: 'round',
  // Spec: 1px at the lightest, 6px at the heaviest, on the default 3px size.
  minWidthRatio: 1 / 3,
  maxWidthRatio: 2,
  sizePresets: [2, 3, 5, 8],
  supportsSnapping: true,
  availableInChildMode: false,
  legacyTool: 'pen',
};

export const BRUSH_PEN: PenPreset = {
  id: 'brush',
  name: 'Brush',
  type: 'brush',
  icon: '🖌',
  group: 'more',
  color: null,
  size: 10,
  opacity: 0.8,
  smoothing: 'high',
  pressureSensitivity: 'high',
  renderMode: 'tapered',
  compositeMode: 'source-over',
  lineCap: 'round',
  minWidthRatio: 0.35,
  maxWidthRatio: 1.5,
  sizePresets: [5, 10, 20, 30],
  supportsSnapping: true,
  availableInChildMode: true,
  legacyTool: 'brush',
};

export const CRAYON_PEN: PenPreset = {
  id: 'crayon',
  name: 'Crayon',
  type: 'crayon',
  icon: '🎨',
  group: 'more',
  color: null,
  size: 12,
  opacity: 1, // Opacity is handled by the texture and overlap naturally
  smoothing: 'low',
  pressureSensitivity: 'medium', // Enable pressure sensitivity to affect line width
  renderMode: 'crayon',
  compositeMode: 'source-over',
  lineCap: 'round',
  textureDensity: 0.65, // Classic crayon
  roughness: 0.5,       // Classic crayon
  minWidthRatio: 0.85,
  maxWidthRatio: 1.25,
  sizePresets: [8, 12, 20, 30],
  supportsSnapping: true,
  availableInChildMode: true,
  legacyTool: 'crayon',
};

export const CALLIGRAPHY_PEN: PenPreset = {
  id: 'calligraphy',
  name: 'Calligraphy',
  type: 'calligraphy',
  icon: '✒',
  group: 'more',
  color: null,
  size: 4,
  opacity: 1,
  smoothing: 'high',
  pressureSensitivity: 'medium',
  renderMode: 'nib',
  compositeMode: 'source-over',
  lineCap: 'butt',
  // 45 degrees: the classic broad-nib angle, thick on the down-stroke.
  nibAngle: Math.PI / 4,
  minWidthRatio: 0.18,
  maxWidthRatio: 1,
  sizePresets: [3, 4, 6, 10],
  supportsSnapping: true,
  availableInChildMode: false,
  legacyTool: 'pen',
};

export const GLOW_PEN: PenPreset = {
  id: 'glow',
  name: 'Glow',
  type: 'glow',
  icon: '✨',
  group: 'more',
  color: '#38bdf8',
  size: 6,
  opacity: 1,
  smoothing: 'medium',
  pressureSensitivity: 'off',
  renderMode: 'glow',
  compositeMode: 'source-over',
  lineCap: 'round',
  glowIntensity: 1,
  sizePresets: [4, 6, 10, 16],
  colorPresets: ['#38bdf8', '#4ade80', '#facc15', '#f472b6'],
  supportsSnapping: true,
  availableInChildMode: false,
  legacyTool: 'marker',
};

export const DOTTED_PEN: PenPreset = {
  id: 'dotted',
  name: 'Dotted',
  type: 'dotted',
  icon: '···',
  group: 'more',
  color: null,
  size: 5,
  opacity: 1,
  smoothing: 'medium',
  pressureSensitivity: 'off',
  renderMode: 'dotted',
  compositeMode: 'source-over',
  lineCap: 'round',
  spacing: 14,
  sizePresets: [3, 5, 8, 12],
  supportsSnapping: true,
  availableInChildMode: false,
  legacyTool: 'pen',
};

export const DASHED_PEN: PenPreset = {
  id: 'dashed',
  name: 'Dashed',
  type: 'dashed',
  icon: '- -',
  group: 'more',
  color: null,
  size: 4,
  opacity: 1,
  smoothing: 'medium',
  pressureSensitivity: 'off',
  renderMode: 'dashed',
  compositeMode: 'source-over',
  lineCap: 'butt',
  dashLength: 16,
  spacing: 12,
  sizePresets: [2, 4, 6, 10],
  supportsSnapping: true,
  availableInChildMode: false,
  legacyTool: 'pen',
};

export const MAGIC_PEN: PenPreset = {
  id: 'magic',
  name: 'Magic Pen',
  type: 'special-pen' as any,
  icon: '✨',
  group: 'more',
  color: null,
  size: 8,
  opacity: 1,
  smoothing: 'high',
  pressureSensitivity: 'medium',
  renderMode: 'glow',
  compositeMode: 'source-over',
  lineCap: 'round',
  minWidthRatio: 0.5,
  maxWidthRatio: 1.5,
  sizePresets: [4, 8, 12, 16],
  supportsSnapping: true,
  availableInChildMode: false,
  legacyTool: 'magic_pen',
};

export const MORE_PENS: PenPreset[] = [
  FOUNTAIN_PEN,
  BRUSH_PEN,
  CRAYON_PEN,
  CALLIGRAPHY_PEN,
  GLOW_PEN,
  DOTTED_PEN,
  DASHED_PEN,
  MAGIC_PEN,
];
