export enum GestureState {
  IDLE = 'IDLE',
  DRAWING = 'DRAWING',
  ERASING = 'ERASING',
  OBJECT_DRAGGING = 'OBJECT_DRAGGING',
  OBJECT_TRANSFORMING = 'OBJECT_TRANSFORMING',
  CANVAS_PANNING = 'CANVAS_PANNING',
  CANVAS_ZOOMING = 'CANVAS_ZOOMING',
  TEACHING_TOOL_INTERACTION = 'TEACHING_TOOL_INTERACTION',
}
